#!/usr/bin/env python

from __future__ import print_function
import os.path
import sys
try:
    import yaml
except ImportError:
    print('Please install PyYaml')
    sys.exit(1)


def main():
    if len(sys.argv) != 3:
        print('Usage {0} module.yaml output.c'.format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    module = []

    with open(input_file) as f:
        module = yaml.load(f)

    form = (
        '// DO NOT EDIT THIS FILE!\n'
        '// This file is autogenerated.\n'
        '// You should edit the source file {infile} instead.\n'
        '\n'
        '{body}'
        '\n')

    line = '  (ngl_obj *) {val},'

    lines = '\n'.join(line.format(val=v['cname']) for v in module)

    body = (
        'ngl_uint {module_name}_length = {length};\n'
        'ngl_obj * {module_name}[] = {{\n'
        '{lines}\n'
        '}};\n')
    module_name = os.path.splitext(os.path.split(input_file)[-1])[0]

    output = form.format(infile=repr(input_file),
                         body=body.format(lines=lines,
                                          length=len(module),
                                          module_name=module_name))

    with open(output_file, 'w') as f:
        f.write(output)


if __name__ == '__main__':
    main()
