#!/usr/bin/env python
from __future__ import print_function

import glob
import os.path
from waf_extensions import declare_variants

declare_variants(subdir='boards')


def build(bld):
    if 'boards' not in bld.variant:
        return
    for board in glob.glob('eda/*.brd'):
        base_name = os.path.split(board)[-1]
        outfile = '../' + os.path.splitext(base_name)[0] + '.zip'
        bld(rule='${root}/tools/run-eagle-cam-v2.py '
                 '${root}/tools/gerber_rules.yaml '
                 '${SRC} ${TGT}',
            source=base_name,
            target=outfile)

    for schematic in glob.glob('eda/*.sch'):
        base_name = os.path.split(schematic)[-1]
        outfile = '../' + os.path.splitext(base_name)[0] + '.csv'
        bld(rule='${root}/tools/generate_bom.py ${SRC} ${TGT} '
                 '${root}/tools/parts-db.yaml',
            source=base_name,
            target=outfile)
