#!/bin/bash

headhash=`git rev-parse HEAD | sed -e 's/\([0-9a-fA-F][0-9a-fA-F]\)/0x\1, /g'`
gitstatus=`git status --porcelain -uno`
if [ -n "$gitstatus" ]
then
	modified="0x01"
else
	modified="0x00"
fi
#echo $headhash$modified

sed -e "s/###DNE###/DO NOT EDIT THIS FILE/g" -e "s/###GITREVISION###/$headhash$modified/g" < $1 > $2
